### ISSUE TITLE
Folder location for Windows .dll & .lua files from moonlibs

### ISSUE THREAD

**Issue by atan2005** [stetre/moongl#5]
I am using Windows 10 Pro (Version 20H2 OS Build 19042.1165) and I have c:\msys64\mingw64 folder hierarchy, installed using https://www.msys2.org/ from a basic msys2 base package (2020.12-1) installation through pacman. I have the following packages installed:-

Development: mingw-w64-x86_64 version of gcc (10.3.0-5), gdb (10.2-2), glew (2.2.0-2), freeglut (3.2.1-2), glfw (3.3.4-1), fltk (1.3.7-1), lua (5.4.3-2), openssl (1.1.1.l-1)

Utility: make (4.3-1), tar (1.34-1), git (2.33.0-1) - as required by moonlibs

I have also managed to git clone and use make to build and install moongl, moonglut, moonglfw, moonfltk, luasocket, luasec packages. The last 2 I have to customize the makefiles to suit my mingw installation.

Note: "c:\msyss64\msys2_shell.cmd" window shell "...MINGW64 ~" (homed at folder c:\msys64\home\username\ ), so various moonlibs git packages are located here.

Under mingw development environment:-
bin\ for .exe & .dll (unarchived)
include\ for .h & .hpp
lib\ for .a & .dll.a (archived versions of .o)

However I have found the mingw generated .dll and accompanied .lua system files (from luasocket & luasec) were incorrectly copied to /lib folder. They should be installed to /bin folder instead for mingw prefix.

Using moongl\src\makefile as example, C_DIR=$(PREFIX)/lib/lua/$(LUAVER) should be C_DIR=$(PREFIX)/bin/lua/$(LUAVER) and etc.

**Comment by stetre** [comment]
Are you sure they should go to /bin ? They are libraries, not executables, so according to the Linux filesystem hierarchy  standard (which mingw replicates) they should go to /lib .

By the way, does this introduce problems, like for example the Lua interpreter not being able to find them?

**Comment by atan2005** [comment]
Use objdump.exe -f <file> to check its BFD flags (bfd_is_relaxable, exec_p, d_paged, dynamic, has_debug, has_lineno, has_locals, has_reloc, has_syms, wp_text) to determine its classification:-

For Windows files below, only consider 7 bits out of the full 10 bits above so excluding (bfd_is_relaxable, dynamic, wp_text).

.exe & .dll => at minimum "exec_p, d_paged, has_reloc", up to full 7 bits.
.a of .o => at minimum "has_syms, has_reloc" and must exclude "exec_p, d_paged", up to full 5 bits. 
.a of .so => at minimum "has_syms" and must exclude "exec_p, d_paged, has_reloc", up to full 4 bits.

I guess the flags will be different for other operating systems but the idea is the same.

For software release in Windows, .dll files are distributed with the associated .exe that needs them at run time (https://docs.microsoft.com/en-us/troubleshoot/windows-client/deployment/dynamic-link-library), in my opinion they should be named .dlb (dynamic linking binary), so they are not to be confused with the archived version of the library files that are stored at lib\ for used during linking stage in makefile. 

The library files usually start with lib*.a (for static linking), lib*.dll.a (for dynamic linking), etc for further software development.

If you review all my 8 pacman development installations above, for example say https://packages.msys2.org/package/mingw-w64-x86_64-lua?repo=mingw64, scroll down to the Files: section, see all the bin\ lib\ includes\ folders and files inside them. They are correctly structured for distribution, hence all lua packages for mingw (and for Windows) should follow the same protocol.

And the following path needs to be added under "System variables" of Windows "Environment variables" setting:-

PATH : "c:\msys64\mingw64\bin\"

For distribution of lua's packages, since lua.exe's 2 default paths were hard-compiled from include\luaconf.h, these 2 paths need to be tailored at run time and best be created using the same approach as Windows PATH above:

LUA_PATH : ".\?.lua;c:\msys64\mingw64\bin\?.lua;c:\msys64\mingw64\bin\lua\5.4\?.lua" (corresponds to lua's package.path)
LUA_CPATH : ".\?.dll;c:\msys64\mingw64\bin\?.dll;c:\msys64\mingw64\bin\lua\5.4\?.dll" (corresponds to lua's package.cpath)

The 3 path settings above are valid for my setup using c:\msys64\mingw64 folder hierarchy and I have no problem in running or locating the generated .exe, .dll, .lua from anywhere inside Windows.

**Comment by stetre** [comment]
Is that a modified luaconf.h ? The original one  actually hardcodes the paths as shown below (taken from lua 5.4.3), which should result in the paths I'm currently using:

```
#if defined(_WIN32)	/* { */
/*
** In Windows, any exclamation mark ('!') in the path is replaced by the
** path of the directory of the executable file of the current process.
*/
#define LUA_LDIR	"!\\lua\\"
#define LUA_CDIR	"!\\"
#define LUA_SHRDIR	"!\\..\\share\\lua\\" LUA_VDIR "\\"

#if !defined(LUA_PATH_DEFAULT)
#define LUA_PATH_DEFAULT  \
		LUA_LDIR"?.lua;"  LUA_LDIR"?\\init.lua;" \
		LUA_CDIR"?.lua;"  LUA_CDIR"?\\init.lua;" \
		LUA_SHRDIR"?.lua;" LUA_SHRDIR"?\\init.lua;" \
		".\\?.lua;" ".\\?\\init.lua"
#endif

#if !defined(LUA_CPATH_DEFAULT)
#define LUA_CPATH_DEFAULT \
		LUA_CDIR"?.dll;" \
		LUA_CDIR"..\\lib\\lua\\" LUA_VDIR "\\?.dll;" \
		LUA_CDIR"loadall.dll;" ".\\?.dll"
#endif
```

**Comment by atan2005** [comment]
The 3 paths I have mentioned above were to be set by user inside their Windows operating system, see 
![moonlibs](https://user-images.githubusercontent.com/88669955/132434608-be3eccdf-291e-4de9-be5e-a64ffaff6462.png). 

The 2 lua paths will be loaded into package.path & package.cpath environment variables upon startup of lua.exe. There is no need to alter luaconf.h.

**Comment by stetre** [comment]
I'd prefer to stick to the current paths, consistently with those chosen by the authors of Lua.

I can however make L_DIR, C_DIR etc overridable, just like LUAVER and PREFIX. Is it ok for you?

**Comment by atan2005** [comment]
No.

The reason is because as soon as your packages were defined for "Mingw" installation through Msys2 shell, the necessary directory locations and file types for Windows have already been pre-defined. Hence it will be invalid to offer customization of folder location (\bin or \lib) or file type (.dll or .so) and so forth. 

The most you can offer is version control preprocessor -DLUAVER=5.4 after -DMINGW, and no other.

MSYS2 focuses on building native software built against the Windows APIs, and they have over 2000 packages that correctly follow Windows convention. I only need to choose the package version required and all are installed correctly with dependency version control as well which is rather brilliant!

Did you review all the folder & file types installed by all 8 pacman packages from Msys2 I have mentioned in my prior post? 

They have the following file structures for Windows software development:-
bin\ for .exe .dll
include\ for .h .hpp
lib\ for .a .dll.a

If you haven't, for each link below, scroll down to respective "Files:" section and inspect their deployed file structures:-

https://packages.msys2.org/package/mingw-w64-x86_64-gcc?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-gdb?repo=mingw64

https://packages.msys2.org/package/mingw-w64-x86_64-glew?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-freeglut?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-glfw?repo=mingw64
https://packages.msys2.org/package/mingw-w64-x86_64-fltk?repo=mingw64

https://packages.msys2.org/package/mingw-w64-x86_64-lua?repo=mingw64  (Notice lua.exe & lua54.dll are in \bin)

https://packages.msys2.org/package/mingw-w64-x86_64-openssl?repo=mingw64

That is why I have challenged against the incorrect location for lua package targeted at Windows operating system that were initiated by most lua authors, after having issues installing the 6 Lua packages, especially luasocket (found bug, refer my post on https://github.com/diegonehab/luasocket/issues/331) and luasec packages.

**Comment by stetre** [comment]
What about this one?

https://packages.msys2.org/package/mingw-w64-x86_64-lua-lpeg?repo=mingw64

**Comment by stetre** [comment]
Lpeg is the archetypal Lua module, and it seems to me that whoever packaged it didn't follow the conventions that according to you should be mandatory, but stuck to those chosen by the author (who is also one of the authors of Lua itself).

By the way, leaving the debate on target directories aside, I too think that Msys2 is great (even if I don't use Windows), but here you are comparing two different things: sources with instructions on how to build and run them, and proper packages like those provided by msys2.org.

I'm fully aware that my libraries aren't properly packaged. For any system,  including the one I use. This is intentional, because I don't have the resources (nor the incentives) to maintain proper packages. My approach then is to keep the build system as simple as possible, so that whoever wants to build them on their system or even package them (if they feel it's worth), can do it without big efforts by customizing or even completely replacing the makefiles. I usually try to be collaborative whenever someone tries to do such things (which I welcome), but I want to make it clear that I don't accept authoritative demands.

**Comment by stetre** [comment]
I took some time to reconsider this issue, and this is what I think about it.

Firstly, there is no Windows convention that states that .dll's should go in /bin: the Windows convention (I believe), is to put them into C:\Windows\System32 or something like that. Since the purpose of Msys2, Mingw, Cygwin and friends is to provide an environment where to build on Windows sources developed for Linux, if there is a convention to be followed by such sources this is the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

However, as you correctly pointed out, most Msys2 packages install .dll files in /bin. If my guess is correct, this is for _convenience_ rather than _convention_. Placing the .dll in the same folder as the binaries that use them relieves the user from editing the Windows enviroment variables to instruct the loader where to find them. This makes sense, I would do the same. But...

But when it comes to Lua modules, the .dll's are not searched for by the loader, but by the binary itself (the Lua interpreter), which by default expects to find them in the standard locations. Putting them in /bin (and the .lua files as well) and then having to set the LUA_PATH and LUA_CPATH would be an unjustified _inconvenience_, rather than a convenience.
